[package]
name = "clp-tdl-package"
version = "0.13.1-dev"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
compression-coordinator = { path = "../compression-coordinator" }
rmp-serde = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
spider-core = { git = "https://github.com/LinZhihao-723/spider.git", branch = "integration-test-dev-compose" }
spider-tdl = { git = "https://github.com/LinZhihao-723/spider.git", branch = "integration-test-dev-compose", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
