/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submits a new query job. */
        post: operations["query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submits a new search job and streams its results back as Server-Sent Events (SSE) in the same response. Only available when the package runs queries on Spider. If the client disconnects before the `end` event, or the job's status can no longer be tracked, the job is marked as cancelling. */
        post: operations["stream_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/{search_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Cancels a previously submitted query job. */
        delete: operations["cancel_query"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query_results/{search_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Streams the results of a previously submitted query as Server-Sent Events (SSE). */
        get: operations["query_results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/compression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets resource usage statistics for compression jobs within the given time range. */
        get: operations["compression_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        CompressionJobStatus: "Pending" | "Running" | "Succeeded" | "Failed" | "Killed";
        /** @description Resource usage statistics for the compression job with the specified ID. */
        CompressionUsage: {
            /**
             * Format: int64
             * @description Total compressed archive size, in bytes.
             */
            compressed_size_bytes: number;
            /**
             * Format: double
             * @description Wall-clock duration the job ran, in seconds. Absent if the job did not complete.
             */
            duration_secs?: number | null;
            /**
             * Format: int32
             * @description Compression job ID.
             */
            id: number;
            /** @description Current status of the job. */
            job_status: components["schemas"]["CompressionJobStatus"];
            /**
             * Format: int32
             * @description Number of tasks the job was split into.
             */
            num_tasks: number;
            /**
             * Format: double
             * @description Sum of all task durations, in seconds. Absent if no tasks reported a duration.
             */
            tasks_duration_secs?: number | null;
            /**
             * Format: int64
             * @description Time the job started executing (epoch milliseconds).
             */
            time_begin_millisecs: number;
            /**
             * Format: int64
             * @description Time the job was created (epoch milliseconds).
             */
            time_creation_millisecs: number;
            /**
             * Format: int64
             * @description Total uncompressed size of input files, in bytes.
             */
            uncompressed_size_bytes: number;
        };
        /** @description Defines the request configuration for submitting a search query. */
        QueryConfig: {
            /**
             * @description Whether to buffer search results in `MongoDB`.
             *     By default, search results are buffered in temporary files. When set to `true`, results
             *     will be stored in `MongoDB` instead.
             */
            buffer_results_in_mongodb?: boolean;
            /**
             * Format: int64
             * @description The size of each time bucket (in milliseconds) for count-by-time aggregation.
             *     When set, the job is submitted as a count-by-time aggregation job instead of a plain
             *     search job, and its results are always buffered in `MongoDB`.
             */
            count_by_time_bucket_size_millisecs?: number | null;
            /** @description The datasets to search within. If not provided, only `default` dataset will be searched. */
            datasets?: string[] | null;
            /** @description Whether the string match should be case-insensitive. */
            ignore_case?: boolean;
            /**
             * Format: int32
             * @description The maximum number of results to return. Set to `0` for no limit.
             */
            max_num_results?: number;
            /** @description The search query as a KQL string. */
            query_string: string;
            /**
             * Format: int64
             * @description The beginning timestamp (in epoch milliseconds) for the search range (inclusive).
             */
            time_range_begin_millisecs?: number | null;
            /**
             * Format: int64
             * @description The ending timestamp (in epoch milliseconds) for the search range (inclusive).
             */
            time_range_end_millisecs?: number | null;
        };
        /**
         * @description Mirror of `job_orchestration.scheduler.constants.QueryJobStatus`. Must be kept in sync.
         * @enum {string}
         */
        QueryJobStatus: "Pending" | "Running" | "Succeeded" | "Failed" | "Cancelling" | "Cancelled" | "Killed";
        QueryResultsUri: {
            /** @description The uri to get the query results. */
            query_results_uri: string;
        };
        /**
         * @description The data of a streaming search's `end` event: the terminal status of the search's query job,
         *     and the search's statistics.
         */
        StreamingSearchEnd: {
            /**
             * Format: int64
             * @description The number of results dropped because a retried search task had already streamed them.
             */
            num_duplicates_dropped: number;
            /**
             * Format: int64
             * @description The number of connections from search tasks closed because they violated the wire protocol.
             */
            num_protocol_errors: number;
            /**
             * Format: int64
             * @description The number of results streamed.
             */
            num_results_emitted: number;
            /** @description The terminal status of the search's query job. */
            status: components["schemas"]["QueryJobStatus"];
        };
        /** @description The data of a streaming search's `error` event. */
        StreamingSearchError: {
            /** @description A description of the error. */
            message: string;
        };
        /** @description The data of a streaming search's `job` event. */
        StreamingSearchJob: {
            /**
             * Format: int32
             * @description The ID of the search's query job.
             */
            query_job_id: number;
        };
        /** @description The data of a streaming search's result event. */
        StreamingSearchResult: {
            /** @description The ID of the archive that contains the result. */
            archive_id: string;
            /** @description The result's log message, without its trailing newline. */
            message: string;
            /**
             * Format: int64
             * @description The result's timestamp (epoch milliseconds).
             */
            timestamp: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "query_string": "*",
                 *       "datasets": [
                 *         "default"
                 *       ],
                 *       "time_range_begin_millisecs": 0,
                 *       "time_range_end_millisecs": 17356896,
                 *       "ignore_case": true,
                 *       "max_num_results": 0,
                 *       "buffer_results_in_mongodb": true,
                 *       "count_by_time_bucket_size_millisecs": null
                 *     }
                 */
                "application/json": components["schemas"]["QueryConfig"];
            };
        };
        responses: {
            /** @description The URI to fetch the results of the submitted query. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "query_results_uri": "query_results/1"
                     *     }
                     */
                    "application/json": components["schemas"]["QueryResultsUri"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "query_string": "*",
                 *       "datasets": [
                 *         "default"
                 *       ],
                 *       "time_range_begin_millisecs": 0,
                 *       "time_range_end_millisecs": 17356896,
                 *       "ignore_case": true
                 *     }
                 */
                "application/json": components["schemas"]["QueryConfig"];
            };
        };
        responses: {
            /** @description Server-Sent Events stream of the search: first a `job` event whose data is a `StreamingSearchJob`, then one unnamed event per result whose data is a `StreamingSearchResult`, and finally an `end` event whose data is a `StreamingSearchEnd`, sent once the job has terminated. If the job's status can't be tracked, an `error` event whose data is a `StreamingSearchError` replaces the `end` event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: job
                     *     data: {"query_job_id":1}
                     *
                     *     data: {"archive_id":"018e90e5-8b2a-4a61-a2fc-cac799936caf","timestamp":1633036800000,"message":"Example log message"}
                     *
                     *     event: end
                     *     data: {"status":"Succeeded","num_results_emitted":1,"num_duplicates_dropped":0,"num_protocol_errors":0}
                     */
                    "text/event-stream": string;
                };
            };
            /** @description The query config is invalid (e.g., an empty `query_string`, an empty `datasets`, or an invalid dataset name), or sets an option that streaming search doesn't support: a nonzero `max_num_results`, `buffer_results_in_mongodb`, or `count_by_time_bucket_size_millisecs`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The package doesn't run queries on Spider. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_query: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancellation request was submitted successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No cancellable query job with the given ID was found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    query_results: {
        parameters: {
            query?: {
                /**
                 * @description When `true`, each SSE event contains the raw result document from the results cache
                 *     serialized as JSON (including metadata such as the timestamp and the original file path);
                 *     otherwise, each event contains only the log message. Only applies to query jobs whose
                 *     results are buffered in `MongoDB`.
                 */
                raw_docs?: boolean;
                /**
                 * @description When `true`, results buffered in `MongoDB` are streamed sorted by timestamp descending;
                 *     otherwise, they're streamed in insertion order. Only applies to query jobs whose results
                 *     are buffered in `MongoDB`.
                 */
                sorted?: boolean;
            };
            header?: never;
            path: {
                search_job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream of query results. Each event contains a single line of the query result in JSON format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example data: {"timestamp": 1633036800, "message": "Example log message"}\n */
                    "text/event-stream": string;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compression_usage: {
        parameters: {
            query: {
                /** @description Start of usage window (epoch milliseconds, inclusive). */
                time_range_begin_millisecs: number;
                /** @description End of usage window (epoch milliseconds, exclusive). */
                time_range_end_millisecs: number;
                /**
                 * @description Job statuses to include as a comma-separated list (e.g.
                 *     `job_status=succeeded,failed`). Recognized values (case-insensitive):
                 *     `PENDING`, `RUNNING`, `SUCCEEDED`, `FAILED`, `KILLED`.
                 *     Defaults to `SUCCEEDED,FAILED,KILLED` (all terminal states).
                 */
                job_status?: string;
                /** @description Maximum number of jobs to return. Must be > 0; defaults to 1000. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompressionUsage"][];
                };
            };
            /** @description Invalid query parameters (e.g., time_range_begin_millisecs > time_range_end_millisecs, missing required fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
